### ISSUE TITLE
New styleguide

### ISSUE THREAD

**Issue by ilarimakela** [RichardLitt/awesome-styleguides#24]
This is kind of ad because I work at SC5 but we have a quite nice styleguide as well. You could go and check it at https://github.com/SC5/sc5-styleguide/ or at http://styleguide.sc5.io/.

There is also nice article about our styleguide so we are not only ones who think it's cool 
http://www.smashingmagazine.com/2015/03/automating-style-guide-driven-development/

**Comment by RichardLitt** [comment]
This looks like it's a tool for building styleguides, but not a styleguide itself. Does that sound right?

**Comment by ilarimakela** [comment]
Yes, that's true.

**Comment by RichardLitt** [comment]
Cool. So, I'm not sure this belongs here, then. Thanks though!
